### ISSUE TITLE
Not able to define optional plus multi valued parameter

### ISSUE THREAD

**Issue by kgaikwad** [mdub/clamp#104]
Trying to define a sub-command where I would like to define parameter that is optional plus multi valued. 
Example - `parameter '[RULES ...]', 'rules to update', :attribute_name => :rules`

I went through below sections:
https://github.com/mdub/clamp#optional-parameters
https://github.com/mdub/clamp#multivalued-aka-greedy-parameters
But not able to define parameter with optional+multi valued together.

Update - with above syntax parameter regex fails for multi valued [clamp/parameter/definition.rb#L16](https://github.com/mdub/clamp/blob/master/lib/clamp/parameter/definition.rb#L16).

**Comment by ofedoren** [comment]
@kgaikwad, I didn't test that, but what if the name of the parameter looks like `[PAR_NAME] ...`?

**Comment by kgaikwad** [comment]
> @kgaikwad, I didn't test that, but what if the name of the parameter looks like `[PAR_NAME] ...`?

Thank you @ofedoren! Yes, I tried by renaming the parameter as you mentioned.
Optional and multi valued are working fine together. 
Closing this issue!
