### ISSUE TITLE
Question: Pass option to subcommand?

### ISSUE THREAD

**Issue by qops1981** [mdub/clamp#119]
Sorry, not an issues I guess, but I am trying to figure out if there is a way to pass an option from one command to a sub command.
Example:
```ruby
#! /usr/bin/env ruby

require 'clamp'
require 'pp'

class SecretsCommand < Clamp::Command

  option "--all", :flag, "all secrets"

  def execute
    pp parse_options
  end

end

class SparkCommand < Clamp::Command

  option ["-e", "--environment"], "Environment", "List the Environment", default: "development" do |s|
    String(s)
  end

  subcommand "secrets", "Initialize the repository", SecretsCommand

end

class SpeakCommand < Clamp::Command

  option "--loud", :flag, "say it loud"
  option ["-n", "--iterations"], "N", "say it N times", default: 1 do |s|
    Integer(s)
  end

  parameter "WORDS ...", "the thing to say", attribute_name: :words

  def execute
    the_truth = words.join(" ")
    the_truth.upcase! if loud?
    iterations.times do
      puts the_truth
    end
  end

end

Clamp do

  subcommand "spark", "Initialize the repository", SparkCommand

  subcommand "speak", "Initialize the repository", SpeakCommand

end
```
How would I pass the "environment" variable to secrets or any other future subcommands?
```shell
./clamp.rb spark -e dev secrets
```
In fairness I have found another library that can make this work either.

**Comment by mdub** [comment]
Hey @qops1981. Yes, that is supported ... but there's a trick. Your main command ("super-command"?) needs to share the option definition with sub-commands. 

You can achieve that by sub-classing a base command, e.g. see [`examples/gitdown`](https://github.com/mdub/clamp/blob/master/examples/gitdown), where the main command and sub-commands all inherit from an `AbstractCommand`. Try

```
bundle exec ./examples/gitdown -v status
bundle exec ./examples/gitdown status -v
```

Or, you can do it using nested, inline `subcommand` class definitions, which essentially creates sub-classes (or the enclosing command class) under the covers. 

FWIW, the code that achieves that is:

https://github.com/mdub/clamp/blob/2bea3050d83d0d6207cff593e58ee4450cf1f8df/lib/clamp/subcommand/execution.rb#L26-L30

**Comment by qops1981** [comment]
Thank you very much!
