### ISSUE TITLE
Invalid @type symbol conversion error

### ISSUE THREAD

**Issue by prof-milki** [mdub/clamp#47]
So, this is **not** a bug in clamp. That's just me being inattentive about the `type` param.

    definition.rb:70:in `+': can't convert Symbol into String (TypeError)

The source was simply a stray `:bool` where a `:flag` should have been.

Anyway. Not big with Ruby, so would it make sense to adapt `Clamp::Option::Definition#help_lhs` nevertheless with:

        lhs += " " + type unless unless type.is_a? Symbol

in place of just `flag?` probing?

**Comment by mdub** [comment]
Not really.  `:flag` is a special-case.
