### ISSUE TITLE
Add :deprecated to options

### ISSUE THREAD

**Issue by jordansissel** [mdub/clamp#50]
I have flags I wish to deprecate, and I'd love it clamp could help with this.

Idea:
* An option with `:deprecated` set will not appear in the usage output (ie; `--help`)
* An option can be declared `:deprecated => "The reason this is deprecated and some other notes"` which can be displayed to users however the application developer decides.[1]
* Add a new method `deprecated_options` intended for use in the `Clamp::Command#execute` method which allows an author to iterate over deprecated options that were given by the user

Rough sketch:

```ruby
class Whoa < Clamp::Command
  option "--really-fast", :flag, "Go fast!", :deprecated => "Please use the --fast flag"
  option "--fast", :flag, "Go fast!"
  
  def execute
    deprecated_options.each do |flag, reason|
      puts "The #{flag} option is deprecated. #{reason}"
    end
  end
end
```

I am willing to provide the patches to achieve this, but I'd like to iterate on the design first before I write some code :)

**Comment by jordansissel** [comment]
The "deprecated_options" thing isn't well-baked in my head. Given environment variables are supported for options, we'll want a way to tell users that a use of an environment variable (via an option) is deprecated.

**Comment by mdub** [comment]
I quite like it.  There's overlap with #46, asking for a `:hidden` flag.

I think it would be best to emit the deprecation warning as part of the writer-method.  In fact, you could do that right now, with something like:

    def really_fast=(value)
      puts "WARNING: --really-fast is deprecated; please use the --fast flag"
      @fast = value
    end

How might you handle/express deprecated _aliases_?

How might you handle/express deprecated _environment variables_?

**Comment by jordansissel** [comment]
@mdub Given :hidden, I think having :deprecated set would *imply* `:hidden => true` and also emit warnings. 

For the writer-method, is your sample something a developer would implement themselves? Or do you see deprecation warnings being generated automatically by Clamp::Attribute::Declaration when it defines the writer method for an option? I suppose my question is more pointedly: should clamp do this? or would the developer using clamp write this custom method per deprecated option? Either answer is fine with me. If clamp should do it, I'll provide code+tests+docs. If the dev should do it, I can write docs (wiki?) for a demonstration.

Either way, I am happy to implement `:hidden` in clamp for #46

**Comment by jordansissel** [comment]
Testing the writer-method-deprecation proposal with #52:

```ruby
Class.new(Clamp::Command) do
  option "--expert", :flag, "Enable expert mode.", :hidden => true, :default => true

  alias_method :orig_expert=, :expert=
  def expert=(value)
    puts "--expert is deprecated! #{value}"
    self.orig_expert = value
  end

  def execute
    puts "Expert mode is on!" if expert?
  end
end.run
```

This seems reasonable. The code is simple enough that I don't know if it is necessary to put into clamp *and* provides a developer with any deprecation notification strategy.

I'll close this since I think :hidden alone is enough from Clamp's side of things.
