### ISSUE TITLE
Upgrade to rspec3-style expect() vs `.should ...`

### ISSUE THREAD

**Issue by jordansissel** [mdub/clamp#51]
In exploration for #50, I was poking around and noticed that clamp uses rspec2 `should` syntax. Any interest in upgrading to rspec3 `expect()` syntax?

I am willing to do the work for this.

**Comment by jordansissel** [comment]
Nevermind, I see you already did it in edfb8dbec422d6f9422bc523369438f3248e8984! I must have an ancient fork :P

**Comment by mdub** [comment]
Beat you to it by a couple of days :-)

**Comment by jordansissel** [comment]
@mdub too fast! :fast_forward: :fast_forward:
