### ISSUE TITLE
support for exit codes

### ISSUE THREAD

**Issue by colinsurprenant** [mdub/clamp#53]
Hi,

Suggestion: It would be nice if the [`run` method](https://github.com/mdub/clamp/blob/2b64126d2067b8e1b5774b65c42340f4ab4921bf/lib/clamp/command.rb#L125) could call `Kernel#exit` with the `execute`return value if not `0` or have another `rescue` clause just for doing `exit(1)` on error. 

This would allow not doing explicit `exit(1)` in a command and be able to still use the command programmatically in another context than command line.

**Comment by mdub** [comment]
Interesting idea.  

But really, `Clamp::Command.run` is pretty short, and exists only to glue the command objects to the real world of ARGV, exceptions, and exit codes.  If you want to drive your command class programmatically, I suggest you bypass `.run`, and just instantiate the Command object directly.  Does that work for you?

**Comment by jordansissel** [comment]
I haven't looked at the code, but if `execute`'s return value is returned from `.run` then I think we can do this ourselvse (outside clamp) for times when we really mean exit, to do: exit(MyCommand.run(args...))

**Comment by mdub** [comment]
Yes, `execute` is the last thing in `Command#run`:

https://github.com/mdub/clamp/blob/master/lib/clamp/command.rb#L67

Let me know if you hit problems.

**Comment by jordansissel** [comment]
Confirmed, SomeCommand.run(args) returns the return value of exit.

@mdub if there's not test coverage for this behavior already, want me to ship you a PR with specs to cover it?

**Comment by mdub** [comment]
Just to clarify, I'm suggesting you use

    SomeCommand.new(...).run(args)

rather than 

    SomeCommand.run(args)

to bypass the default exception handling.  Perhaps you should even bypass "command-line" parsing and set attributes directly, e.g.

    cmd = SomeCommand.new(...)
    cmd.some_option = "blah de blah"
    cmd.execute

I'm more than happy to accept tests for behaviour you think is too loosely specified.

**Comment by colinsurprenant** [comment]
yeah, agree, makes more sense to handle exit behaviour outside of clamp around our call `run`.
