### ISSUE TITLE
Option / flag order

### ISSUE THREAD

**Issue by alex-phillips** [mdub/clamp#56]
When parsing, it seems the order of options / flags and arguments matters.

Ex:
`command --option arg`

But if I type
`command arg --option`

It fails. `ERROR: Too many arguments`

Could this be resolved so the order of parameters doesn't matter? (Obviously order of arguments would matter, but not flags / options)

**Comment by mdub** [comment]
Well, no, this is intrinsic to the way Clamp parses the command line; options come before positional parameters.  That's also an assumption made by most command-line parsers I know of.

**Comment by mdub** [comment]
What is your concrete use-case? If `arg` is essentially a sub-command, then you could model it that way. In Clamp subcommands may take their own options/parameters, and will inherit options set on the "parent" command.

**Comment by alex-phillips** [comment]
`arg` in this case is a subcommand. My use-case is just if you run a command and forget a parameter, you could just hit up arrow and tack it onto the end. I've written an arg parser in PHP and the order of parameters didn't matter, so wasn't sure if it was an easy change or not. Just a convenience question.

**Comment by mdub** [comment]
Ok. If it's declared as `subcommand` in Clamp, and you declare the option on the parent command, then you should get the behaviour you want. Let me know how you go. If it doesn't work, a code snippet would be useful.

**Comment by mickey** [comment]
I have the exact same use case. I have a `dump` command with 2 subcommands `table` and `database`.
Declaring an option `--database-url` on the `dump` command, will have the following effect:

```sh
❯ my_cli dump database --database-url "mysql2://exemple.com"
ERROR: Unrecognised option '--database-url'

See: 'my_cli dump database --help'
```

```my_cli dump --database-url "mysql2://exemple.com database``` works as expected.

**Comment by mickey** [comment]
Here's a code example to demonstrate the issue:

```ruby
#! /usr/bin/env ruby

require "clamp"
require "clamp/version"

class TableCommand < Clamp::Command
  def execute
    puts "table dumped"
  end
end

class DatabaseCommand < Clamp::Command
  def execute
    puts "database dumped"
  end
end

class DumpCommand < Clamp::Command
  option "--database-url", "DATABASE_URL", "Database URL", environment_variable: "DATABASE_URL"#, required: true

  subcommand "table", "Dump one or more tables", TableCommand
  subcommand "database", "Dump a database", DatabaseCommand
end

class MainCommand < Clamp::Command
  subcommand "dump", "Dump database", DumpCommand
end

MainCommand.run
```

```sh
❯ ./test.rb dump --help
Usage:
    test.rb dump [OPTIONS] SUBCOMMAND [ARG] ...

Parameters:
    SUBCOMMAND                    subcommand
    [ARG] ...                     subcommand arguments

Subcommands:
    table                         Dump one or more tables
    database                      Dump a database

Options:
    --database-url DATABASE_URL   Database URL (default: $DATABASE_URL)
    -h, --help                    print help
```

First the `help` option combined with the subcommand doesn't show the `--database-url` option:
```sh
❯ ./test.rb dump database --help
Usage:
    test.rb dump database [OPTIONS]

Options:
    -h, --help                    print help
```

And finally as expected it fails on:
```sh
❯ ./test.rb dump database --database-url
ERROR: Unrecognised option '--database-url'

See: 'test.rb dump database --help'
```

**Comment by mdub** [comment]
@mickey If you want an option to be accepted by both the parent command AND subcommands, it needs to be declared on both. 

Furthermore, it's not sufficient to duplicate the option declaration; you have to actually do it in a shared base-class, or a module.  For example:

```ruby
class BaseCommand < Clamp::Command
  option "--database-url", "DATABASE_URL", "Database URL", environment_variable: "DATABASE_URL"#, required: true
end

class TableCommand < BaseCommand
  def execute
    puts "table dumped"
  end
end

class DatabaseCommand < BaseCommand
  def execute
    puts "database dumped"
  end
end

class DumpCommand < BaseCommand
  subcommand "table", "Dump one or more tables", TableCommand
  subcommand "database", "Dump a database", DatabaseCommand
end

class MainCommand < BaseCommand
  subcommand "dump", "Dump database", DumpCommand
end

MainCommand.run
```

If you use the block form of `subcommand`, Clamp sorts it out for you, by generating sub-classes:

```ruby

Clamp do

  option "--database-url", "DATABASE_URL", "Database URL", environment_variable: "DATABASE_URL"#, required: true

  subcommand "dump", "Dump database" do

    subcommand "table", "Dump one or more tables" do
      def execute
        puts "table dumped"
      end
    end

    subcommand "database", "Dump a database" do
      def execute
        puts "database dumped"
      end
    end

  end

end
```

**Comment by mdub** [comment]
Closing this ... but feel free to continue the conversation.

**Comment by mickey** [comment]
Oh I see, thanks a lot for the explanation and detailed implementation.
