### ISSUE TITLE
Getting parameters and options dynamically from the execute method

### ISSUE THREAD

**Issue by nleib** [mdub/clamp#58]
I am using the Clamp in a tool where its parameters and options are dynamically created from a config file. This means that I only know during run time what are my params/options/flags.

When I get to writing the execute method I would like to have the ability to go over all params/options/flags... and send them to my program.

example:

```ruby
Clamp do
  #Declarations of all parameters and options....

def execute
  options_and_their_values = self.get_options
  parameters... = self.get_params
 MyProgramClass.new(options_and_their_values)
end

end #end clamp
```
In this example I could send all params/options and their values without knowing what they are in run time.

I would like to hear what you think.

**Comment by mdub** [comment]
You could do that using `self.class.recognised_options` and `self.class.parameters`, e.g.

```ruby
Clamp do

  option ["--foo"], "FOO", "optional foo"

  parameter "BAR", "a bar"

  def execute
    self.class.recognised_options.each do |opt|
      value = send(opt.read_method)
      puts "option #{opt.attribute_name} = #{value.inspect}"
    end
    self.class.parameters.each do |param|
      value = send(param.read_method)
      puts "parameter #{param.attribute_name} = #{value.inspect}"
    end
  end

end
```

A word of warning: they're not really part of Clamp's public interface.  Having said that, I've no plans to make changes in that area.

**Comment by nleib** [comment]
Thanks for this info
