### ISSUE TITLE
How to define --version 

### ISSUE THREAD

**Issue by kke** [mdub/clamp#68]
It's quite common to have something like `app --version` output the version.

How to do this with clamp if you have subcommands in your main command?

How about other "global" options/flags such as `['-d', '--debug']`?

**Comment by mdub** [comment]
For `--version` I typically do something like:

```ruby
option "--version", :flag, "Show version" do
  puts MyGem::VERSION
  exit(0)
end
```

For global options, it's just a matter of declaring them at the top-level (most abstract) level, e.g.

```ruby
Clamp do

  option ["-v", "--verbose"], :flag, "be verbose"

  subcommand "foo", ...
  subcommand "bar", ...

end
```

after which you can specific them either before or after the subcommand:

```
demo --verbose foo
demo foo --verbose
```

Both are demonstrated in https://github.com/mdub/clamp/blob/master/examples/gitdown
