### ISSUE TITLE
"setup" method for global initialization?

### ISSUE THREAD

**Issue by ronen** [mdub/clamp#72]
Hi, thanks for the great gem.

In my current use, I have to do some initialization based on the global option values.  I can define a `setup` method in my `Clamp` block, but then I need to call it at the start of each of my `execute` methods.

I wonder if you'd be interested in a PR that would DRY that up, automatically calling an optional `setup`?

It seems implementation would be easy, at [command.rb#L61](https://github.com/mdub/clamp/blob/master/lib/clamp/command.rb#L61):

```ruby
def run(arguments)
  parse(arguments)
  setup
  execute
end

def setup
  # base does nothing, sub-class can override 
end
```

That's all that I need for my current application, but one could also imagine going whole hog and providing `setup`, `teardown`, and `around`:

```ruby
def run(arguments)
  parse(arguments)
  begin
    setup
    around do
      execute
    end
  ensure
    teardown
  end
end

def setup
  # base does nothing, sub-class can override 
end

def around
  yield # base does nothing interesting, sub-class can override
end

def teardown
  # base does nothing, sub-class can override
end
```

...but that might be overkill.

What do you think?  I'm happy to submit a PR but don't want to put in the time for the specs etc if you're not up for it.  Also could debate the names of the methods, the execution order of `setup`/`teardown` vs `around`, etc.

Thanks again

**Comment by mdub** [comment]
`setup` seems like a decent idea. 

I don't see a need for `around`, or `teardown`, as commands typically exit after execution.

**Comment by mdub** [comment]
I'm going to close this. It's a nice idea, but I'm worried it would cause angst for users who happen to have defined a `setup` method in their commands.
