### ISSUE TITLE
Included parameter/option defaults do not work as expected

### ISSUE THREAD

**Issue by kke** [mdub/clamp#75]
Not necessarily a bug, but something of an annoyance.

## This works as expected and documented:

```ruby
class FooCommand < Clamp::Command

  parameter "[FOO]", "Foo"

  def default_foo
    "bar"
  end

  def execute
    puts foo
  end
end

FooCommand.run
```

## But this does not:

```ruby
module CommonParam
  def self.included(where)
    where.parameter "[FOO]", "Foo"
  end

  def default_foo
    "bar"
  end
end

class FooCommand < Clamp::Command

  include CommonParam

  def execute
    puts foo
  end
end

FooCommand.run
```

The `default_foo` will never be called. 

I believe this is because the default_method is defined during declaration and not "on the spot".

## A workaround like this can be used:

```ruby
module CommonParam

  def self.included(where)
    where.prepend InstanceMethods
    where.parameter "[FOO]", "Foo"
  end

  module InstanceMethods
    def default_foo
      "bar"
    end
  end
end

class FooCommand < Clamp::Command

  include CommonParam

  def execute
    puts foo
  end
end

FooCommand.run
```

**Comment by mdub** [comment]
That is kind of annoying, isn't it?

Another possible workaround might be `remove_method`, e.g.

```ruby
module CommonParam

  def self.included(where)
    where.parameter "[FOO]", "Foo"
    where.remove_method(:default_foo)
  end

  def default_foo
    "bar"
  end

end
```

I reckon it's because Clamp currently _always_ defines a `default_NAME` method when declaring a parameter (or option). I guess I could change it to avoid declaring such a method when the default is `nil`.
