### ISSUE TITLE
required:true breaks attribute writer functionality

### ISSUE THREAD

**Issue by wesm-outreach** [mdub/clamp#77]
### This Works

```
#! /usr/bin/env ruby

require "clamp"

Clamp do
  option %w(--foo), 'FOO[:THING]',
         'A fooy thing',
         attribute_name: :fooilicious

  def fooilicious=(thing)
    @my_att = thing
  end

  def execute
    puts @my_att
  end
end

```
>Output
```
$ ./required-setter-overwritten --foo bar
bar
```

### This Fails
```diff
#! /usr/bin/env ruby

require "clamp"

Clamp do
  option %w(--foo), 'FOO[:THING]',
         'A fooy thing',
         attribute_name: :fooilicious,
+        required: true

  def fooilicious=(thing)
    @my_att = thing
  end

  def execute
    puts @my_att
  end
end
```

> Output
```
$ ./required-setter-overwritten --foo bar
ERROR: option '--foo' is required

See: 'required-setter-overwritten --help'
```

**Comment by wesm-outreach** [comment]
It seems this can be fixed by adding
`@fooilicious = thing` to the end of the attribute writer. I think that maybe this should be called out in the readme?

**Comment by wesm-outreach** [comment]
Thinking about this more... the logic to determine if a value was provided to an option or parameter should happen _before_ any custom validation/handling. Here's the reason, using the example in the readme:

```ruby
parameter "SERVER", "location of server"

def server=(server)
  @server_address, @server_port = server.split(":")
end
```

if `server` is nil, `server.split(":")` will fail.

**Comment by mdub** [comment]
Clamp uses "attribute" in the same sense as Ruby's built-in `attr_{reader,writer,accessor}` methods, which provide access to a instance-variable of the same name. As such, there's an assumption that a writer-method whether custom of generated will set the namesake ivar, e.g. `#fooilicious=` should set `@fooilicious`.  So, this would work:

```ruby
Clamp do

  option %w(--foo), 'FOO', 'A fooy thing',
         attribute_name: :fooilicious,
         required: true

  def fooilicious=(arg)
    @fooilicious = arg
  end

  def execute
    puts @fooilicious
  end

end
```

I'm not sure what you mean about "logic to determine if a value was provided". Are you referring to the check that all "required" options are set? Assuming so, it's easier to do that after attempting to set options from the command-line, and environment-variables. Note that it's not possible to provide a `nil` argument via the command-line.

**Comment by wesm-outreach** [comment]
Going back to the example in the Readme...

```Ruby
parameter "SERVER", "location of server"

def server=(value)
  @server_address, @server_port = value.split(":")
end
```

the requirement from the user is that the `SERVER` parameter is set. Yet this validation happens _after_ that attribute writer is called, (and a value, whether it's an empty string or not) is attempted to be manipulated into something useful.

**Comment by mdub** [comment]
In the case of a missing (required) parameter, the attribute-writer will actually never be called; instead a "no value provided" error will be signalled, when we run out of command-line arguments.

I'm confused, Wes - I thought your issue related to options? Has my recommendation above - that you use conventional instance-variable names - solved the problems you were having?

**Comment by wesm-outreach** [comment]
sorry, you are right, it is related to options. The example in the readme was for a parameter, but the idea holds true for options. The attribute writer is called before `required` is evaluated. I think that's all I'm getting at at this point. I think the `required` should look at the value it sends to the attribute writer to see if it's empty/nil, then raise.

**Comment by mdub** [comment]
Sorry to leave this hanging so long.

The intent of `:required` was to guard against certain options _not_ being specified on the command-line. It's not intended validate the value provided, and I don't want to extend the semantics to do so.

If you want to validate that the value provided (for an option) is not blank, you can/should do so in the attribute writer, e.g.

```ruby
parameter "SERVER", "location of server"

def server=(value)
  raise ArgumentError, "cannot be blank" if value.empty?
  @server_address, @server_port = value.split(":")
end
```
