### ISSUE TITLE
Suggestion: 'execute do' instead of 'def execute'

### ISSUE THREAD

**Issue by DannyBen** [mdub/clamp#84]
Not sure if this was considered before and ruled out or not, but something that strikes me as a little odd in the syntax for creating an application with Clamp, is the fact that it has a `def execute` inside of a block. I don't recall seeing such an approach anywhere (but of course it may just mean that I have not seen enough gems...).

I was wondering if it would make sense to change or amend the syntax so that it will allow the use of `execute do` block, like so: 

```ruby
Clamp do
  subcommand "test", "Test it" do
    option "--loud", :flag, "say it loud"

    execute do
      ...
    end
  end
end
```

This feels a little more natural to me.

**Comment by mdub** [comment]
Interesting feedback,@DannyBen. It's never struck me as odd that `#execute` is a method, as the whole point of Clamp is modelling commands as classes, and command executions as instances. But with so much other DSL hiding the class definition, I can see what you mean.

Your suggestion is actually pretty easy to implement:

```ruby
module Clamp
  class Command
    class << self
      def execute(&block)
        define_method(:execute, &block)
      end
    end
  end
end
```
