### ISSUE TITLE
Parameter ARGF like functionality

### ISSUE THREAD

**Issue by kke** [mdub/clamp#87]
With current Clamp I often find it a bit complicated to handle input from either STDIN or a filename passed as parameter.

(Even more so if you try to mix in a default value for the filename (which is quite usual nowadays in many apps, if you have some `Dockerfile`, `docker-compose.yml`, `Whateverfile` in your current dir, it will be used by default if you omit the parameter).)

I believe [Ruby's ARGF](https://ruby-doc.org/core-2.1.1/ARGF.html) was made because it's such a common thing you have to deal with when making command line apps.

So, wouldn't it be super fantastic if you could do this:

```ruby
Clamp do
  parameter '[FILE]', "File path", default: 'config.yml', argf: true
end
```

The value of `file` would then be either:
1. `File.read(file) if file`
2. `$stdin.read unless $stdin.tty?`
3. `File.read('config.yml')`
4. nil

(maybe it should signal_usage_error if param is given and there's something coming from stdin)

This would work a bit like the ruby `ARGF`:

```
# argf.rb
puts ARGF.read

$ ruby argf.rb file.txt
file.txt content

$ echo "hello" | ruby argf.rb
hello

# This I don't quite like about ARGF for my usecases because it's super difficult
# to separate the files:
$ ruby argf.rb file.txt file2.txt file3.txt
file.txt content
file2.txt content
file3.txt content
```

I have no idea if Ruby's ARGF can be used at all together with Clamp, probably not. Also it has some special abilities like the in place editing `-i`.

Another variation of the same type of scenario, but more easy to do with current clamp is:

```ruby
Clamp do
  parameter '[FILE ...]', "File path"

  def default_file_list
     if $stdin.tty? #  perhaps something more elegant for checking is available?
       Array.new
     else
       $stdin.read.split(/\s+/)
     end
   end
end
```

Now you can do:
```
$ command x.txt y.txt z.txt
# or: (without using "xargs")
$ ls *.txt | command 
```

Not too difficult, but maybe this too could be handled by Clamp for you:

```ruby
Clamp do
  parameter '[FILE ...]', "File path", default: 'file.txt', stdin: true
end
```

**Comment by mdub** [comment]
Sounds cool. I imagine one could achieve such a result using a helper object, e.g.

```ruby
Clamp do

  parameter "[FILE ...]", "Input file(s)"

  def execute
    combined_input = ArgfLikeThing.new(file_list)
    combined_input.each_line do |line|
      ...
    end
  end

end
```

Building `ArgfLikeThing` is left as an exercise for the reader :-)

I don't think such functionality should be built into Clamp; it could easily be a standalone gem.
