### ISSUE TITLE
Negative numbers passed as parameter as interpreted a options

### ISSUE THREAD

**Issue by anibalrojas** [mdub/clamp#91]
I tried forcing the interpretation as a parameter with -- and it didn't work.

**Comment by mdub** [comment]
Ouch!

Can you provide a minimal example to demonstrate the problem, @anibalrojas? A Clamp command declaration, and example command invocation.

**Comment by mdub** [comment]
Ah, no, that's expected behaviour. 

```
$ /tmp/clamp_negative_params.rb -1
ERROR: Unrecognised option '-1'

See: 'clamp_negative_params.rb --help'
```

As you suspected, you need to explicitly terminate the option list, if you want it interpreted as a positional parameter. I'm not sure why that didn't work for you, @anibalrojas, as it works for me:

```
$ /tmp/clamp_negative_params.rb -- -1
-1
```
