### ISSUE TITLE
Clamp apps testing

### ISSUE THREAD

**Issue by anibalrojas** [mdub/clamp#93]
I suppose you have built at least one Clamp "app" with the library you developed :-) Do you have any recommendations you could when it comes to testing a command built on Clamp?

**Comment by mdub** [comment]
Please excuse the slow reply.

It depends a lot on what you're testing, how much logic is in your CLI layer, and to what extent you can decouple other logic from the CLI.

In the [Clamp test-suite](https://github.com/mdub/clamp/blob/master/spec/clamp/command_spec.rb), I instantiate `Command` subclasses programatically, poke them with `parse` and `run`, and observe the effects. But there I'm very much testing the behaviour of Clamp itself.

If you want to test your CLI layer - ie. option/parameter handling logic, and the behaviour of your `execute` method - you could take a similar approach. Create a new instance of your command class, call `parse` (or attribute-writer methods) to configure it, call `execute`, and observe the effects. To isolate the CLI layer, you may wish to inject mocks or stubs for your "backend" code.

[swa](https://github.com/mdub/swa) is a Clamp-based AWS CLI. It has no tests. It's really just wraps AWS API calls, and I haven't felt the need.

[Stackup](https://github.com/realestate-com-au/stackup) is a library and CLI for managing CloudFormation stacks. The "library" part is exhaustively tested, but again, there are no tests for the CLI layer.

[Pith](https://github.com/mdub/pith) is my static-site generator. I have a suite of Cucumber tests there, but yet again, they bypass the CLI "porcelain" and call the underlying code directly.

At my last employer we created a Clamp-based deployment tool. In that case, we _did_ have a suite of tests, which executed a fresh deployment of an app, then various upgrades, and finally tore it down. I wrote that test suite in Bash, executing the tool with various arguments, and checking output.

If your command interacts primarily with the local filesystem, you may find [Aruba](https://github.com/cucumber/aruba) useful. 

I hope that helps.

**Comment by anibalrojas** [comment]
Wow! Thanks a lot for such elaborate response, almost a post :)  Checking Aruba as I am actually doing stuff with the filesystem
