### ISSUE TITLE
[BUG] default value is not passed to subcommand

### ISSUE THREAD

**Issue by BobVanB** [mdub/clamp#95]
Code
```
  class CLI < Clamp::Command
    option ["-l", "--log-level"], "level", "Setting logging level. (D>I>W>E>F)", attribute_name: :logger, default: "mydefault" do |level|
      level
    end

    subcommand "host", "host actions" do
      def execute
        puts inspect
      end
    end
```
Without argument
```
cli host
#<#<Class:0x000000020f11b0>:0x000000020f7d80 @invocation_path="cli host", @context={}, @remaining_arguments=[]>
```
With argument
```
cli  --log-level DEBUG host
#<#<Class:0x000000030ace88>:0x000000030b2c98 @invocation_path="cli host", @context={}, @logger="DEBUG", @remaining_arguments=[]>
```
My question, when i give a default value, why is this not added to the subcommand as attribute?

**Comment by BobVanB** [comment]
https://github.com/mdub/clamp/pull/96/files

please change according to your own nameing and add a exception where i am surely missing one.

**Comment by mdub** [comment]
Hi Bob.

Default values are provided by defining methods. Attribute read methods will look for a default if the attribute hasn't be set explicitly. As such, there's no need to proactively set attribute instance-variables to default values. The code in question is at:

* https://github.com/mdub/clamp/blob/b590719afd225e71b715efa0ed92340ae9cb1593/lib/clamp/attribute/instance.rb#L31-L39

For instance, a command defined with:

```ruby
Clamp do

  option ["-l", "--log-level"], "level", "Setting logging level. (D>I>W>E>F)", default: "mydefault"

  subcommand "show", "show stuff" do
    def execute
      puts "log-level = #{log_level}"
    end
  end

end
```

has the following behaviour:

```
$ ./examples/issue-95 show
log-level = mydefault

$ ./examples/issue-95 -l other show
log-level = other
```

I hope that helps. Is the way defaulting works causing some kind of problem for you?

**Comment by BobVanB** [comment]
The way you describe is, that everything is going into one ruby class.

This is my situation:
```
module MyModule
  require 'clamp'

  class Show < Clamp::Command
    def execute
      puts "log-level = #{log_level}"
    end
  end

  class CLI < Clamp::Command
    option ["-l", "--log-level"], "level", "Setting logging level. (D>I>W>E>F)", default: "mydefault"
    subcommand "show", "show stuff", Show
  end
end
```
results in `NameError: undefined local variable or method`
When i use @log_level, results in `log-level = `

**Comment by mdub** [comment]
To get proper option "inheritance" between and parent command and subcommands, it's best to declare the option in a common ancestor (or a commonly included module). One gets that for free using inline subcommand declarations. In your case, I suggest declaring a common base class, as follows:

```ruby
module MyModule

  class BaseCommand < Clamp::Command
    option ["-l", "--log-level"], "level", "Setting logging level. (D>I>W>E>F)", default: "mydefault"
  end

  class Show < BaseCommand
    def execute
      puts "log-level = #{log_level}"
    end
  end

  class CLI < BaseCommand
    subcommand "show", "show stuff", Show
  end

end
```
